image:
  repository: ghcr.io/nayetdet/mirro-world
  tag: latest
  pullPolicy: IfNotPresent

schedule: "0 0 * * 1"
timeZone: America/Fortaleza
config:
  gitlabUrl: https://gitlab.com
  includeForks: true
  includeArchived: true
  override: false

externalSecret:
  name: mirro-world
  storeName: vault
  refreshInterval: 1h
  remoteKey: mirro-world

persistence:
  size: 1Gi
  storageClass: ""
